# Generated by Django 5.1.2 on 2024-10-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecipe',
            fields=[
                ('title', models.CharField(db_index=True, max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('created_by', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
